### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by ghamerly** [petrrysavy/siamsdm2016presentation#1]
https://github.com/petrrysavy/siamsdm2016presentation/blob/05ae82c380e639ef7fae56e15e4ef61746bad684/presentation.tex#L63

I get a compilation error starting here due to missing files.

**Comment by petrrysavy** [comment]
I appologize, this https://github.com/petrrysavy/siamsdm2016presentation/commit/b9e5e0c98ca126bdbf912acc6178f4ef063abaaa commit should fix that.

**Comment by petrrysavy** [comment]
Sorry, there are few more

**Comment by petrrysavy** [comment]
This time it should be ok: https://github.com/petrrysavy/siamsdm2016presentation/commit/fcc6814680de8e6a046656dd6837c32b9d001fb2

**Comment by ghamerly** [comment]
Thanks.
