### ISSUE TITLE
Arithmetic overflow with titleprogressbar@tmpdim

### ISSUE THREAD

**Issue by ghamerly** [petrrysavy/siamsdm2016presentation#2]
I get this error now:

```
Overfull \vbox (0.67711pt too high) detected at line 509
[45]
! Arithmetic overflow.
\progressbar@titleprogressbar ...ar@tmpdim by 100 
                                                  \par \begin {tikzpicture}[...
l.516 \end{frame}

? 
```

**Comment by petrrysavy** [comment]
Sorry for late reply. Appologize me, but this looks like a difference between MikTeX on W10 and (?) TexLive on MacOs. I do not get that error. I turned off the titleprogressbar, so the problem should not arise again. But I am not sure about that. See commit https://github.com/petrrysavy/siamsdm2016presentation/commit/73d411ca8a312dfc99e778bfd9ccd604d94aba81

**Comment by ghamerly** [comment]
It builds! Thanks.
